baseURL = "http://georgiastuart.com"
languageCode = "en-us"
title = "Georgia Stuart"

[params]
    email = "georgia.stuart@gmail.com"
    github = "georgiastuart"
    linkedin = "georgiastuart"
    website = "georgiastuart.com"
#staticDir = ["static"]

[[menu.navbar]]
name = "About"
url = "about"

[[menu.navbar]]
name = "Blog"
url = "blog"

[[menu.navbar]]
name = "Teaching"
url = "teaching"

[[menu.navbar]]
name = "Tim"
url = "https://tullrich.com"

[[menu.navbar]]
name = "UTD"
url = "http://utdallas.edu"