baseURL = "http://georgiastuart.com"
languageCode = "en-us"
title = "Georgia Stuart"

#staticDir = ["static"]

[[menu.navbar]]
name = "About"
url = "about"

[[menu.navbar]]
name = "Blog"
url = "blog"

[[menu.navbar]]
name = "Teaching"
url = "teaching"

[[menu.navbar]]
name = "Tim"
url = "https://tullrich.com"
