[[education]]
date = "December 2019"
degree = "Doctor of Philosophy in Applied Mathematics"
institution = "The University of Texas at Dallas"
location = "Richardson, TX"
notes = "Concentration in numerical methods for stochastic seismic inversion. \
        Advisors: Dr. Susan Minkoff and Dr. Felipe Pereira"
